--- #YAML:1.0
name:               App-Pod2CpanHtml
version:            0.04
abstract:           Convert Pod to search.cpan.org style HTML.
author:
    - John McNamara (jmcnamara@cpan.org)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Pod::Simple:  0
    perl:         5.005
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
